---

- name: install jupyterhub dependencies via conda
  conda: name={{item}} state=present
  become: true
  with_items:
    - configurable-http-proxy
    - sqlalchemy

- name: install jupyterhub via pip
  pip: name={{item}} state=present editable=false
  become: true
  with_items:
    - jupyterhub==0.7
    - oauthenticator==0.5
    - notebook
    - jupyterhub-systemdspawner
#    - jupyterhub-ldapauthenticator

- name: install jupyterhub ldapautheticator via pip
  pip: name={{item}} state=forcereinstall editable=false
  become: true
  with_items:
    - git+https://github.com/gkdb/ldapauthenticator
